### ISSUE TITLE
No version for package.json

### ISSUE THREAD

**Issue by rcline** [segmentio/analytics.js-integration#47]
Hey!

There is no version in the package.json file, so when trying to install this integration directly it errors out. Seems this is the same for most the integrations. Thanks!!!

**Comment by ndhoule** [comment]
This is partially by design; individual integrations are not designed for standalone use. Up until recently all integrations used Duo, which doesn't use npm.

As of recently you'll be able to install this package via npm, but you should carefully examine your use case—more likely than not you should use this package through a built analytics.js distribution rather than by installing it directly.
